### ISSUE TITLE
Should percent encode the query key and value when being encoded as str

### ISSUE THREAD

**Issue by xiren7** [gruns/furl#100] opened 2018-06-02 10:47 UTC
I use furl(v1.1) in http proxy app,  and receive url in server side(the http proxy received from client):

```python
>>> url_received = 'http://example.com/?redirect=http%3A%2F%2Fwww.example.com%2F'
>>> parsed = furl.furl(url_received)
```

After do something with the parsed url, and generate url in client side(to be sent to the real server):

```python
>>> url_to_be_sent = parsed.url 
>>> print(url_to_be_sent)
'http://example.com/?redirect=http://www.example.com/'
>>> print(url_to_be_sent.query)
'redirect=http://www.example.com/'
```

Should the "redirect=http://www.example.com/" part be percent encoded as original query "redirect=http%3A%2F%2Fwww.example.com%2F"?

**Comment by gruns** [comment] 2018-06-06 21:46
> Should the "redirect=http://www.example.com/" part be percent encoded as
> original query "redirect=http%3A%2F%2Fwww.example.com%2F"?

`"redirect=http://www.example.com/"` doesn't need to be percent encoded; `.`,
`:`, and `/` are all valid query characters.

Is the URL `http://example.com/?redirect=http://www.example.com/` rejected by
the receiving software? That's a perfectly valid URL.

**Comment by gruns** [comment] 2018-06-06 23:48
It's ambiguous. Both

 * `http://host/?q=://`

and

 * `http://host/?q=%3A%2F%2F`

are perfectly valid URLs, so furl has a choice of what to do here.

> But should not be decoded in query neither?

The equality

```python
url == furl(url).url
```

is not a goal of furl. There are many URLs that furl happily accepts where that
equality fails. Like

```python
>>> from furl import furl
>>> url = 'https://www.google.com/a b/?a=a b'
>>> f = furl(url)
>>> f.url
'https://www.google.com/a%20b/?a=a+b'
>>> url == f.url
False
```

Zooming out, is there a reason you'd prefer furl to encode `.:/` (and their ilk)
in query strings? Is `http://example.com/?redirect=http://www.example.com/`
rejected by software you're using?

**Comment by xiren7** [comment] 2018-06-07 00:16
> Is http://example.com/?redirect=http://www.example.com/
rejected by software you're using?

Yes. I used furl in a proxy server. 
The client sent me the url with query be percent encoded. 
I parsed the url with furl, and forwarded the `furl(url).url` to the server, the server complained about the url.

> Zooming out, is there a reason you'd prefer furl to encode .:/ (and their ilk)
in query strings?

I did not know why the client encode the query as percent encoding.

I suggest furl only decode or encode the reserved characters. But not the `:` or `/`.

**Comment by gruns** [comment] 2018-06-07 00:53
> I parsed the url with furl, and forwarded the furl(url).url to the server, the
> server complained about the url.

Interesting.

Which server software complained about

 * `http://example.com/?redirect=http://www.example.com/`

? And what was the warning or error message, if available?

As aforementioned, `http://example.com/?redirect=http://www.example.com/` is a
perfectly valid URL.


If URLs like `http://host/?q=://` prove problematic for existing software in the
wild, even though they shouldn't, furl should switch from

 * `http://host/?q=://`

to

 * `http://host/?q=%3A%2F%2F`

**Comment by xiren7** [comment] 2018-06-07 01:51
I think the client encode the query component with `encodeURIComponent`, it encode all the unsafe characters, including `:` and `/`. 

> Which software complained about the URL `http://example.com/?redirect=http://www.example.com/`
?

I really did not know what the http parser the server(*.backend.semrush.com) in my case used.

> `http://host/?q=://` to `http://host/?q=%3A%2F%2F` to be safe.

I agree, maybe the best way is to encode all the unsafe characters.

**Comment by gruns** [comment] 2018-06-07 03:35
I'm afraid I don't quite follow. Can you elaborate on what you mean by

> the server hashed the url, and sent the hash value with the query

So if `http://example.com/?redirect=http://www.example.com/` is the input URL,
what is the final URL that `backend.semrush.com` receives? That is, what is
`http://example.com/?redirect=http://www.example.com/` turned into after

> the server hashed the url, and sent the hash value with the query

?

**Comment by xiren7** [comment] 2018-06-07 07:10
> I'm afraid I don't quite follow. Please elaborate on what you mean by
```python
# client side
# the pseudo code for simulating what client do
target = encodeURIComponent("http://target.com/") # js function encodeURIComponent
print(target) # -> "http%3A%2F%2Ftarget.com%2F"
hash = hash_with_md5(target)
print(hash) # -> "2063c1608d6e0baf80249c42e2be5804"
original_url_sent_by_client = f"http://server/?q={target}&h={hash}"

# proxy server side
parsed_url = furl(original_url_sent_by_client)
# do log some values in the parsed_url
...
# proxy client side
url_to_be_sent = parsed_url.url
print(url_to_be_sent) # -> "http://server/?q=http://target.com/&h=2063c1608d6e0baf80249c42e2be5804"
httpclient.send(url_to_be_sent)
# because the query value changes from "http%3A%2F%2Ftarget.com%2F" to "http://target.com/"
# so the hash value will not match, and the real server complains about that.
```

From https://en.wikipedia.org/wiki/Query_string:
HTML 5 specifies the following transformation for submitting HTML forms with the "get" method to a web server.[1] The following is a brief summary of the algorithm:
* Characters that cannot be converted to the correct charset are replaced with HTML numeric character references[11]
* SPACE is encoded as '+' or '%20'
* Letters (A–Z and a–z), numbers (0–9) and the characters '*','-','.' and '_' are left as-is
* '+' is encoded by %2B
* All other characters are encoded as %HH hex representation with any non-ASCII characters first encoded as UTF-8 (or other specified encoding)

According to the algorithm, only `Letters (A–Z and a–z), numbers (0–9) and the characters '*','-','.' and '_' are left as-is`, all other characters are transformed. 
At least for the query part, I think should encode what decoded. For example:

```python
decode(encode(' ')) == ' '
encode(decode('%20'))) = '%20'

decode(encode('=')) == '='
encode(decode('%3D'))) = '%3D'

decode(encode(':')) == ':'
encode(decode('%3A')) == '%3A' # the current furl will return encoded value as ':' not '%3A'

decode(encode('/')) == '/'
encode(decode('%2F')) == '%2F' # the current furl will return encoded value as '/' not '%2F'
```

**Comment by gruns** [comment] 2018-06-07 09:03
Aha!

Thank you for the example with pseudo code. Your situation makes perfect sense
now.

Fundamentally, `furl.url` will not always exactly reproduce the URL it was fed,
like my prior example:

```
>>> furl('https://www.google.com/a b/?a=a b').url
'https://www.google.com/a%20b/?a=a+b'
```

In all these scenarios, the hash of `furl(url).url` will differ from the hash of
the original URL, `url`.

While as per RFC 3986 `/` and `:` are perfectly valid query characters

```
query         = *( pchar / "/" / "?" )
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
pct-encoded   = "%" HEXDIG HEXDIG
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
              / "*" / "+" / "," / ";" / "="
```

furl's decision not to encode them clearly leads to problems.

I'll change furl's encoding scheme to percent encode sub-delim characters, too.

**Comment by gruns** [comment] 2018-06-21 08:05
Fixed in https://github.com/gruns/furl/commit/68b0cb9bdf8c7f00f9ec62947c506d538dc76f7f.

This fix will ship in the next version of furl, v1.2.

**Comment by xiren7** [comment] 2018-06-21 15:55
Thanks for the library.

**Comment by gruns** [comment] 2018-06-30 01:51
The aforementioned query encoding overhaul shipped in Furl v1.2.

```python
>>> f = furl('http://example.com/')
>>> f.args['redirect'] = 'http://www.example.com/'
>>> f.url
'http://example.com/?redirect=http%3A%2F%2Fwww.example.com%2F'
```

Upgrade with

```
pip install furl --upgrade
```

Thank you for bringing this issue to my attention, @xiren7. Don't hesitate to
let me know if there's anything else I can do for you.

**Comment by youtux** [comment] 2018-08-29 08:07
I cannot upgrade to furl 1.2 because of the change in 68b0cb9. I am using furl to return URLs containing query params that are also URLs to applications developed by third parties. Some of them may not use proper decoding, and if I upgrade to version 1.2 I will be breaking compatibility with those apps.
Is there a way to have the old behavior back, maybe by adding a parameter to the `tostr()` function?

**Comment by gruns** [comment] 2018-09-12 20:27
@youtux Interesting. Thank you for weighing in.

Before I add a parameter to `tostr()` to optionally disable query encoding (i.e.
revert https://github.com/gruns/furl/commit/68b0cb9bdf8c7f00f9ec62947c506d538dc76f7f), which sites and/or libraries "may not use proper decoding"?
Are you sure compatiblity would be broken?

If so, is it realistic to reach out and ask them to switch to proper URL
handling libraries and/or tools?

**Comment by youtux** [comment] 2018-09-14 08:49
It is not easy for me to reach them, and to be honest it would be quite time-consuming. But I saw many application just taking "parsing" query params by splitting the URL with the `&` character and then splitting again each item with `=` to fetch key and value, without doing any unquoting.

**Comment by youtux** [comment] 2018-10-08 15:12
Thanks for your support, Ansgar. I’m going to check it out on Wednesday and
I’ll let you know, but from your explaination of the change it’s looking
good.

**Comment by youtux** [comment] 2018-10-10 11:36
I am trying it using commit c30edb2077152187bdfb39dfc7629e6258765d51, but I think I found a bug:
```python
import furl

embedded_url = furl.furl('https://example.com/foos/21312312321312312?a=1&b=2')
assert set(embedded_url.args) == {'a', 'b'}

wrapping_url = furl.furl('https://mydomain.com/').set(args={'foo': embedded_url}).tostr(query_dont_quote=True)
assert set(furl.furl(wrapping_url).args) == {'foo'}  # This fails, 'b' is parsed as an query param of wrapping_url.
```
The problem is that we don't escape `?` and `&` chars when using query_dont_quote=True. If I am correct, tostr should always try to restrict the choice of characters the user is telling to not quote, in case it is not allowed.

**Comment by gruns** [comment] 2018-10-17 18:54
Thanks for testing, @youtux!

> The problem is that we don't escape ? and & chars when using
> query_dont_quote=True.

The problem is that it's impossible to satisfy both the above and:

> But I saw many application just taking "parsing" query params by splitting the
> URL with the & character and then splitting again each item with = to fetch
> key and value, without doing any unquoting.

If the receiving application extracts query parameters by spliting `&` and not
unquoting percent-encoded characters, then the encoded `?` and `&` characters in

```
'https://example.com/foos/21312312321312312%3Fa=1%26b=2'
```

will be incorrectly parsed as the raw strings `%3F` and `%26`, respectively, not
`?` and `&`, as you intend.


This is the original problem I highlighted: furl can only do so much to insulate
against lamentable software that ignorantly splits on `&` and doesn't unquote
percent-encoded characters.


Nonetheless, if you want encode `?` and `&` in your example, you can do so like:

```
>>> from furl import furl, Query
>>> safe = ''.join(set(Query.SAFE_VALUE_CHARS) - set('?&'))
>>> url = 'https://example.com/foos/21312312321312312?a=1&b=2'
>>> furl('https://mydomain.com/').set(args={'foo': url}).tostr(query_dont_quote=safe)
```

Does this suffice for your needs?

If not, I will remove the `dont_quote=` and `query_dont_quote=` parameters to
keep furl's API lean. The fault here lies not with furl, but the reprehensible
software that doesn't properly decode percent-encoded characters, as per RFC
3986.

**Comment by youtux** [comment] 2018-10-19 09:29
The failing test case that I reported has little to do with my specific problems of application doing a naive split on `&`.
What I reported is that with the change you suggested, `tostr` is going to create wrong urls when used with `query_dont_quote=True`. Instead, it should try to not quote as much as possible, but still being escaping character that must be escaped in the query params.
I am suggesting to remove `&` from the list of safe characters, just like it used to be in version 1.1.

**Comment by youtux** [comment] 2018-11-09 14:15
@gruns any update on this?

**Comment by gruns** [comment] 2018-11-16 07:33
@youtux Thank you for the ping.

I'll look into this again soon. At first glance, your suggestion to

> I am suggesting to remove & from the list of safe characters, just like it
> used to be in version 1.1.

seems solid.

**Comment by gruns** [comment] 2018-11-29 05:16
@youtux I removed `&` from Query's SAFE_KEY_CHARS list. With such,
your prior example

```python
import furl

embedded_url = furl.furl('https://example.com/foos/21312312321312312?a=1&b=2')
assert set(embedded_url.args) == {'a', 'b'}

wrapping_url = furl.furl('https://mydomain.com/').set(args={'foo': embedded_url}).tostr(query_dont_quote=True)
assert set(furl.furl(wrapping_url).args) == {'foo'}  # This fails, 'b' is parsed as an query param of wrapping_url.
```

now runs without `AssertionError`s. URLs can now be encoded as query
parameters without issue, even with `query_dont_quote=True)`.

Does this solve your original problem?

**Comment by youtux** [comment] 2018-12-16 11:56
Yes, it does. Would you mind adding this scenario to the test suite?

**Comment by gruns** [comment] 2019-02-06 23:17
I added more tests in https://github.com/gruns/furl/commit/e9855e86162fe679ce15d38d6bda67e6041f2a1b.

The aforementioned `query_dont_quote=` parameter of `furl.tostr()` will ship in
the next version of furl, v2.1.0. Then your prior example will work beautifully:

```python
>>> from furl import furl
>>> url = 'https://example.com/?a=1&b=2'
>>> set(furl(url).args)
{'a', 'b'}
>>> furl(url).set(args={'foo': url}).tostr()
'https://example.com/?foo=https%3A%2F%2Fexample.com%2F%3Fa%3D1%26b%3D2'
>>> f = furl(url).set(args={'foo': url})
>>> f.tostr(query_dont_quote=True)
'https://example.com/?foo=https://example.com/?a=1%26b=2'
>>> set(f.args)
{'foo'}
```

I will close this Issue once v2.1.0 ships.

**Comment by youtux** [comment] 2019-02-09 14:58
It looks like it does. Thanks for taking care of it, @gruns, much appreciated.

**Comment by youtux** [comment] 2019-07-22 09:21
@gruns Any plan to release 2.1.0 anytime soon?

**Comment by gruns** [comment] 2019-11-26 16:57
Furl v2.1.0 released!

```
$ pip install furl --upgrade
```

Closing this Issue, now resolved with the addition of `query_dont_quote=`.

Thank you for your help and input @xiren7 and @youtux. Don't hesitate to let me know if there's anything else I can do for you.

**Closed by gruns** 2019-11-26 16:57 UTC
